In [2]:
import pandas as pd
import numpy as np

In [3]:
import talib  # библиотека для расчёта индикаторов

In [4]:
from utils import parabolic_sar

In [5]:
N = 20

In [6]:
# 1. Загрузка данных
# Предполагаем, что есть CSV с колонками: datetime, open, high, low, close, volume
# df = pd.read_csv('dowload_data/CNYRUBF_1Min.txt', parse_dates=['datetime'], index_col='datetime')
def readQuotes(path):
    try:
        quotes = pd.read_csv(path, sep=';')
        quotes['date'] = quotes['date'] + ' ' + quotes['time']
        del quotes['time']
        quotes['date'] = pd.to_datetime(quotes['date'], format='%d.%m.%Y %H:%M:%S', errors='raise', dayfirst=True)
        quotes.index = quotes['date']
        quotes.index.name = 'Date'
        del quotes['date']
        quotes[quotes.columns].astype(float)
        return quotes
    except pd.errors.EmptyDataError:
        print(f"File {path} is empty")
        return pd.DataFrame()
    except pd.errors.ParserError as e:
        print(f"Error parsing file {path}: {e}")

In [7]:
df_history = readQuotes('..\dowload_data\YDEX_1Day.txt')
# readQuotes('..\dowload_data\CNYRUBF_15Min_history.txt')
#readQuotes('..\dowload_data\YDEX_4HOUR.txt')
#readQuotes('..\dowload_data\SBER_1Day_history.txt')

df_history.tail()

              open    high     low   close   volume
Date
2025-05-22  3990.0  4089.0  3925.0  4024.0   773429
2025-05-23  4032.0  4048.0  3996.0  4009.5   335512
2025-05-26  4002.5  4024.0  3886.0  3917.0   504972
2025-05-27  3917.5  4024.0  3855.0  3992.5   694856
2025-05-28  3998.0  4176.0  3995.0  4165.0  1192435

In [8]:
df_history['EMA'] = talib.EMA(df_history['close'], timeperiod=20)
df_history['SAR'] = parabolic_sar(df_history['high'], df_history['low'])

In [397]:
# ЛОНГ
# падающая -> растущая -> растущая
df_history['pattern'] = (df_history['close'].shift(2) < df_history['open'].shift(2)) & \
            (df_history['close'].shift(1) > df_history['open'].shift(1)) & \
            (df_history['close'] > df_history['open']) & \
            (
                (df_history['EMA'].shift(2) < df_history['high'].shift(2)) & \
                (df_history['EMA'].shift(1) < df_history['high'].shift(1)) & \
                (df_history['EMA'] < df_history['high'])
            )

max_ = 0
max_inx = 0
for i in range(2, N):
    df_history['next_2_candles'] = df_history['open'].shift(-1) < df_history['close'].shift(-i)

    st = df_history[df_history['pattern']]['next_2_candles'].mean()
    if max_ < st:
        max_ = st
        max_inx = i

if max_ > 0.49:
    print(max_inx, max_)

14 0.5714285714285714

In [398]:
# ШОРТ
# растущая -> падающая -> падающая
df_history['pattern'] = (df_history['close'].shift(2) > df_history['open'].shift(2)) & \
            (df_history['close'].shift(1) < df_history['open'].shift(1)) & \
            (df_history['close'] < df_history['open']) & \
            (
                (df_history['EMA'].shift(2) > df_history['high'].shift(2)) & \
                (df_history['EMA'].shift(1) > df_history['high'].shift(1)) & \
                (df_history['EMA'] >  df_history['high'])
            )

max_ = 0
max_inx = 0
for i in range(2, N):
    df_history['next_2_candles'] = df_history['open'].shift(-1) > df_history['close'].shift(-i)

    st = df_history[df_history['pattern']]['next_2_candles'].mean()
    if max_ < st:
        max_ = st
        max_inx = i

if max_ > 0.49:
    print(max_inx, max_)

13 0.6486486486486487

In [399]:
# ЛОНГ
# поглощение падющей свечи
df_history['pattern'] = (df_history['close'].shift(1) < df_history['open'].shift(1)) & \
            (df_history['open'] >= df_history['close'].shift(1)) & \
            (df_history['close'] >= df_history['open'].shift(1)) & \
            (
                (df_history['EMA'].shift(2) > df_history['low'].shift(2)) & \
                (df_history['EMA'].shift(1) > df_history['low'].shift(1)) & \
                (df_history['EMA'] > df_history['low'])
            )

max_ = 0
max_inx = 0
for i in range(2, N):
    df_history['next_2_candles'] = df_history['open'].shift(-1) < df_history['close'].shift(-i)
    # df_history['next_2_candles'] = (df_history['high'].shift(-i) - df_history['open'].shift(-1)) > 0.01

    st = df_history[df_history['pattern']]['next_2_candles'].mean()
    if max_ < st:
        max_ = st
        max_inx = i

if max_ > 0.29:
    print(max_inx, max_)

4 0.5294117647058824

In [400]:
# ШОРТ
# поглощение растущей свечи
df_history['pattern'] = (df_history['close'].shift(1) > df_history['open'].shift(1)) & \
            (df_history['open'] >= df_history['close'].shift(1)) & \
            (df_history['close'] <= df_history['open'].shift(1)) & \
            (
                (df_history['EMA'].shift(2) > df_history['high'].shift(2)) & \
                (df_history['EMA'].shift(1) > df_history['close'].shift(1)) & \
                (df_history['EMA'] >  df_history['high'])
            )

max_ = 0
max_inx = 0
for i in range(2, N):
    df_history['next_2_candles'] = df_history['open'].shift(-1) > df_history['close'].shift(-i)

    st = df_history[df_history['pattern']]['next_2_candles'].mean()
    if max_ < st:
        max_ = st
        max_inx = i

if max_ > 0.49:
    print(max_inx, max_)

2 0.5161290322580645

In [403]:
# ЛОНГ
# продлжение падения ( растет -> падает -> падает)
df_history['pattern'] = (df_history['close'].shift(2) > df_history['open'].shift(2)) & \
            (df_history['close'].shift(1) < df_history['open'].shift(1)) & \
            (df_history['close'] > df_history['open']) & \
            (
                (df_history['EMA'].shift(2) < df_history['low'].shift(2)) & \
                (df_history['EMA'].shift(1) < df_history['low'].shift(1)) & \
                (df_history['EMA'] <  df_history['low'])
            )

max_ = 0
max_inx = 0
for i in range(2, N):
    # df_history['next_2_candles'] = df_history['open'].shift(-1) < df_history['close'].shift(-i)
    df_history['next_2_candles'] = (
        df_history['high'].shift(-i) - df_history['open'].shift(-1)
        ) > 40

    st = df_history[df_history['pattern']]['next_2_candles'].mean()
    if max_ < st:
        max_ = st
        max_inx = i
        # df_history[df_history['pattern']]['next_2_candles']

if max_ > 0.19:
    print(max_inx, max_)

3 0.6842105263157895

In [102]:
df_history.tail(77)

,open,high,low,close,volume,EMA,SAR,pattern,next_2_candles
Date,,,,,,,,,
2025-03-01,4450.0,4455.0,4427.0,4438.0,13967,4421.068015,4709.621980,False,-154.0
2025-03-02,4430.5,4432.5,4365.0,4376.0,40558,4416.775823,4676.852222,False,-254.0
2025-03-03,4392.5,4399.5,4260.0,4347.5,1105947,4410.178126,4646.704044,False,-199.5
2025-03-04,4368.0,4619.5,4356.0,4586.0,1426446,4426.923066,4260.000000,False,139.5
2025-03-05,4585.5,4630.0,4470.0,4497.0,924568,4433.597060,4267.190000,True,141.0
...,...,...,...,...,...,...,...,...,...
2025-05-22,3990.0,4089.0,3925.0,4024.0,773429,4061.205966,3882.780625,False,NaN
2025-05-23,4032.0,4048.0,3996.0,4009.5,335512,4056.281588,3888.925012,False,NaN
2025-05-26,4002.5,4024.0,3886.0,3917.0,504972,4043.016675,4190.000000,False,NaN
2025-05-27,3917.5,4024.0,3855.0,3992.5,694856,4038.205563,4183.920000,False,NaN
2025-05-28,3998.0,4176.0,3995.0,4165.0,1192435,4050.281224,3855.000000,False,NaN

In [410]:
df_history[df_history['pattern'] & df_history['next_2_candles']]['next_2_candles'].loc['2024-03-01':]

Date
2024-11-05    True
2024-11-18    True
2024-11-22    True
2025-04-10    True
Name: next_2_candles, dtype: bool

In [409]:
# ШОРТ
# продлжение падения (падает -> растет -> падает)
df_history['pattern'] = (df_history['close'].shift(2) < df_history['open'].shift(2)) & \
            (df_history['close'].shift(1) > df_history['open'].shift(1)) & \
            (df_history['close'] < df_history['open']) & \
            (
                (df_history['EMA'].shift(2) > df_history['high'].shift(2)) & \
                (df_history['EMA'].shift(1) > df_history['high'].shift(1)) & \
                (df_history['EMA'] >  df_history['high'])
            )

max_ = 0
max_inx = 0
for i in range(2, N):
    # df_history['next_2_candles'] = df_history['open'].shift(-1) > df_history['close'].shift(-i)
    df_history['next_2_candles'] = (
        df_history['open'].shift(-1) - df_history['low'].shift(-i)
    ) > 40

    st = df_history[df_history['pattern']]['next_2_candles'].mean()
    if max_ < st:
        max_ = st
        max_inx = i

if max_ >= 0.49:
    print(max_inx, max_)

2 0.5263157894736842

In [36]:
# ЛОНГ
# SAR под ценой, цена выше EMA
df_history['pattern'] = \
            (df_history['SAR'].shift(2) > df_history['high'].shift(2)) & \
            (df_history['SAR'].shift(1) < df_history['low'].shift(1)) & \
            (df_history['SAR'] < df_history['open']) & \
            (df_history['open'] > df_history['EMA'])

max_ = 0
max_inx = 0
for i in range(2, N):
    # df_history['next_2_candles'] = \
    #     df_history['open'].shift(-1) < df_history['close'].shift(-i)
    df_history['next_2_candles'] = \
        (df_history['close'].shift(-i) - df_history['open'].shift(-1)) #> 20

    st = df_history[df_history['pattern']]['next_2_candles'].mean()
    # print(st)
    if max_ < st:
        max_ = st
        max_inx = i
        # df_history[df_history['pattern']]['next_2_candles']

if max_ > 0.19:
    print(max_inx, max_)

12 8.719999999999981

In [37]:
df_history['next_2_candles'] = \
        (df_history['close'].shift(-6) - df_history['open'].shift(-1))
df_history[df_history['pattern']].tail(65)

,open,high,low,close,volume,EMA,SAR,pattern,next_2_candles
Date,,,,,,,,,
2023-11-29,2602.2,2628.8,2563.6,2574.0,902549,2589.643770,2542.388,True,-226.2
2024-06-06,4180.0,4238.0,4151.4,4204.2,261180,4153.476638,3896.512,True,-74.3
2025-01-31,4117.0,4154.0,4057.0,4092.0,758059,3986.152607,3927.970,True,136.0
2025-03-06,4498.0,4577.5,4480.0,4513.5,561254,4441.206864,4267.190,True,14.0
2025-05-14,4115.5,4154.0,4021.0,4021.0,364017,4088.789959,3821.520,True,20.0

In [92]:
df_history.tail(30)

,open,high,low,close,volume,EMA,SAR,pattern,next_2_candles
Date,,,,,,,,,
2025-04-23,4362.5,4382.0,4182.0,4285.0,1088953,4257.622729,3883.271898,False,265.0
2025-04-24,4287.0,4372.5,4245.0,4293.0,584541,4260.991993,3914.485584,False,206.5
2025-04-25,4301.5,4374.0,4294.0,4371.5,759468,4271.516565,3943.826449,False,216.5
2025-04-28,4322.5,4358.0,4237.0,4283.0,844808,4272.610226,3971.406862,False,231.0
2025-04-29,4285.0,4316.5,4131.5,4155.0,538880,4261.409252,3997.332450,False,113.5
2025-04-30,4154.0,4211.0,3993.0,4106.0,712587,4246.608371,4403.500000,False,122.5
2025-05-02,4113.0,4113.0,3900.0,3905.5,561471,4214.121859,4395.290000,False,-84.0
2025-05-03,3940.0,3960.0,3909.0,3940.5,61146,4188.062634,4375.478400,False,-64.5
2025-05-04,3945.0,3976.0,3940.0,3948.5,50717,4165.247145,4356.459264,False,38.0
2025-05-05,3955.0,3975.0,3814.0,3860.0,616394,4136.175989,4338.200893,False,-132.5
2025-05-06,3860.0,4065.5,3817.0,4013.0,787680,4124.444942,4306.748840,False,-150.0
2025-05-07,4015.0,4092.0,3961.0,3991.0,726515,4111.735900,4277.183909,False,NaN
2025-05-08,3991.0,4058.5,3987.0,3993.5,234269,4100.475338,4249.392875,False,NaN
2025-05-10,4008.5,4012.0,3993.5,3997.0,27073,4090.620544,4223.269302,False,NaN
2025-05-11,4075.0,4093.5,4041.5,4060.0,94491,4087.704302,4198.713144,False,NaN
2025-05-12,4080.5,4190.0,4080.5,4153.5,746321,4093.970559,3814.000000,False,NaN
2025-05-13,4158.0,4180.5,4072.5,4114.5,418666,4095.925744,3821.520000,False,NaN
2025-05-14,4115.5,4154.0,4021.0,4021.0,364017,4088.789959,3828.889600,False,NaN
2025-05-15,4020.5,4060.5,3924.0,3989.5,895960,4079.333772,3836.111808,False,NaN
2025-05-16,3997.5,4069.5,3910.0,4022.0,738567,4073.873413,3843.189572,False,NaN
2025-05-17,4022.0,4107.0,4022.0,4095.0,75066,4075.885469,3850.125780,False,NaN
2025-05-18,4109.5,4128.0,4083.0,4106.0,52172,4078.753519,3856.923265,False,NaN
2025-05-19,4108.5,4115.5,4032.5,4054.0,566174,4076.396041,3863.584799,False,NaN
2025-05-20,4064.0,4091.0,4021.0,4040.5,318991,4072.977371,3870.113104,False,NaN
2025-05-21,4042.0,4050.0,3971.0,3990.5,308074,4065.122383,3876.510841,False,NaN
2025-05-22,3990.0,4089.0,3925.0,4024.0,773429,4061.205966,3882.780625,False,NaN
2025-05-23,4032.0,4048.0,3996.0,4009.5,335512,4056.281588,3888.925012,False,NaN
2025-05-26,4002.5,4024.0,3886.0,3917.0,504972,4043.016675,4190.000000,False,NaN
2025-05-27,3917.5,4024.0,3855.0,3992.5,694856,4038.205563,4183.920000,False,NaN
2025-05-28,3998.0,4176.0,3995.0,4165.0,1192435,4050.281224,3855.000000,False,NaN

In [1]:
%load_ext autoreload
%autoreload 2

import os
from datetime import datetime, timedelta
import pandas as pd
import numpy as np
from tqdm.auto import tqdm

from utils import readQuotes, MEDIAN, ATR, EMA, PERCENTILE, calculate_linear_regression_rolling

In [4]:
import pandas as pd
import numpy as np
from statsmodels.tsa.vector_ar.vecm import coint_johansen
from statsmodels.tsa.stattools import coint
import os

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
tiсkers = []
with open('../download_data/temp.txt', 'r') as file:
    for t in file.readlines():
        t = t[:-1]  # отрываем символ переноса строки
        tiсkers.append(t)

In [24]:
df_by_ticker = dict()
for ticker in tiсkers:
    try:
        df_base = readQuotes(f'..\download_data\{ticker}\{ticker}_1W_history.txt')
        df_by_ticker[ticker] = df_base#[['close']]
    except Exception:
        print(ticker)

In [7]:
# Объединение всех данных по времени
def merge_data(data_dict):
    merged_df = pd.DataFrame(index=data_dict[list(data_dict.keys())[0]].index)
    for name, df in data_dict.items():
        merged_df = merged_df.join(df.rename(columns={'close': name}), how='outer')
    return merged_df.dropna()

In [10]:
# Тест на коинтеграцию между всеми парами
def check_cointegration(df):
    instruments = df.columns
    results = {}
    for i in range(len(instruments)):
        for j in range(i + 1, len(instruments)):
            series1 = df[instruments[i]]
            series2 = df[instruments[j]]

            # Тест Энгеля-Гранжера (для пары)
            coint_t, p_value, crit_vals = coint(series1, series2)

            results[(instruments[i], instruments[j])] = {
                'p-value': p_value,
                'coint_t': coint_t
            }
    return results

In [49]:
def check_cointegration_johansen(ts1, ts2, det_order=0, k_ar_diff=1):
    """
    Проверяет коинтеграцию между двумя временными рядами по тесту Йохансена
    """
    df = pd.concat([ts1, ts2], axis=1).dropna()
    if df.shape[0] < max(100, 3 * (k_ar_diff + 1)):  # Минимум для теста
        return False  # Недостаточно данных

    try:
        result = coint_johansen(df, det_order, k_ar_diff)
        # result.lr1 — trace statistics
        # result.cvt — критические значения (0: 90%, 1: 95%, 2: 99%)
        trace_stat = result.lr1[0]
        crit_value_95 = result.cvt[0][1]  # 95% уровень значимости
        return trace_stat > crit_value_95
    except Exception as e:
        print(f"Ошибка при тестировании коинтеграции: {e}")
        return False

def find_cointegrated_pairs(data_dict, det_order=0, k_ar_diff=1):
    """
    Находит все коинтегрированные пары из словаря с временными рядами (тест Йохансена)
    """
    symbols = list(data_dict.keys())
    pairs = []

    for i in range(len(symbols)):
        for j in range(i + 1, len(symbols)):
            s1 = data_dict[symbols[i]]['close'].apply(math.log)
            s2 = data_dict[symbols[j]]['close'].apply(math.log)

            is_cointegrated = check_cointegration_johansen(s1, s2, det_order, k_ar_diff)

            if is_cointegrated:
                pairs.append((symbols[i], symbols[j]))

    return pairs

In [45]:
import math

In [48]:
math.log(12)

2.4849066497880004

In [50]:
merged_data = df_by_ticker#merge_data(df_by_ticker)

In [55]:
len(merged_data)

72

In [53]:
# Найти коинтегрированные пары с помощью теста Йохансена
cointegrated_pairs = find_cointegrated_pairs(merged_data, det_order=0, k_ar_diff=1)

In [56]:
print("Коинтегрированные пары (по тесту Йохансена):")
for pair in cointegrated_pairs:
    print(f"{pair[0]} - {pair[1]}")
print(len(cointegrated_pairs))

Коинтегрированные пары (по тесту Йохансена):
AFKS - ALRS
AFKS - CHMF
AFKS - GAZP
AFKS - HYDR
AFKS - IRAO
AFKS - LKOH
AFKS - MAGN
AFKS - MOEX
AFKS - MSNG
AFKS - MTLR
AFKS - MTLRP
AFKS - MTSS
AFKS - NLMK
AFKS - NVTK
AFKS - OZPH
AFKS - PHOR
AFKS - PIKK
AFKS - PLZL
AFKS - PRMD
AFKS - RASP
AFKS - ROSN
AFKS - RTKM
AFKS - RTKMP
AFKS - RUAL
AFKS - SMLT
AFKS - SNGS
AFKS - SNGSP
AFKS - SPBE
AFKS - SVCB
AFKS - T
AFKS - TATN
AFKS - TATNP
AFKS - TRMK
AFKS - VSEH
AFKS - YDEX
AFLT - DATA
AFLT - DIAS
AFLT - LSRG
AFLT - PHOR
AFLT - RENI
AFLT - SPBE
AKRN - DATA
AKRN - LEAS
AKRN - LENT
AKRN - MAGN
AKRN - PHOR
AKRN - RAGR
AKRN - RENI
AKRN - SMLT
AKRN - SPBE
AKRN - SVCB
AKRN - T
AKRN - VKCO
AKRN - WUSH
ALRS - DATA
ALRS - HYDR
ALRS - LEAS
ALRS - MAGN
ALRS - MTLR
ALRS - MTLRP
ALRS - PLZL
ALRS - RAGR
ALRS - RASP
ALRS - RTKM
ALRS - RTKMP
ALRS - RUAL
ALRS - SMLT
ALRS - SNGS
ALRS - VKCO
ALRS - VSEH
ALRS - VSMO
AQUA - CBOM
AQUA - DATA
AQUA - LEAS
AQUA - PHOR
AQUA - RNFT
AQUA - UPRO
AQUA - VKCO
AQUA - VSEH
AQUA - YDEX
BELU - PRMD
BELU - VKCO
BELU - VSEH
BELU - YDEX
CBOM - ENPG
CBOM - LKOH
CBOM - LSRG
CBOM - PHOR
CBOM - PLZL
CBOM - RNFT
CBOM - ROSN
CBOM - RUAL
CBOM - SBERP
CBOM - SPBE
CBOM - TRNFP
CBOM - VSEH
CBOM - WUSH
CHMF - GAZP
CHMF - HYDR
CHMF - IRAO
CHMF - IVAT
CHMF - KMAZ
CHMF - LKOH
CHMF - MAGN
CHMF - MOEX
CHMF - MSNG
CHMF - MTLR
CHMF - MTLRP
CHMF - NLMK
CHMF - NVTK
CHMF - PHOR
CHMF - PIKK
CHMF - PLZL
CHMF - RAGR
CHMF - RASP
CHMF - RNFT
CHMF - ROSN
CHMF - RTKM
CHMF - RTKMP
CHMF - SBER
CHMF - SBERP
CHMF - SELG
CHMF - SNGS
CHMF - SNGSP
CHMF - TATN
CHMF - TRMK
CHMF - VKCO
CHMF - VSEH
CHMF - VSMO
CNRU - DATA
CNRU - LSRG
CNRU - PLZL
CNRU - RASP
CNRU - RENI
CNRU - RNFT
CNRU - SBER
CNRU - SBERP
CNRU - T
CNRU - TRMK
CNRU - WUSH
DATA - HNFG
DATA - LEAS
DATA - LSRG
DATA - MAGN
DATA - MOEX
DATA - MTLR
DATA - MTLRP
DATA - MVID
DATA - NLMK
DATA - RASP
DATA - SELG
DATA - VSEH
DATA - WUSH
DIAS - MOEX
DIAS - SVAV
ENPG - NVTK
ENPG - RENI
ENPG - RUAL
ENPG - SPBE
ENPG - SVCB
ENPG - T
ENPG - VKCO
ENPG - YDEX
EUTR - HEAD
EUTR - OZPH
EUTR - PRMD
EUTR - RAGR
EUTR - SGZH
EUTR - VSEH
EUTR - X5
EUTR - YDEX
FLOT - IVAT
FLOT - LKOH
FLOT - MBNK
FLOT - MSNG
FLOT - PHOR
FLOT - RNFT
FLOT - ROSN
FLOT - VSEH
GAZP - LENT
GAZP - MAGN
GAZP - NLMK
GAZP - RAGR
GAZP - RENI
GAZP - RUAL
GAZP - SPBE
GAZP - SVCB
GAZP - VSMO
GMKN - RAGR
GMKN - RASP
GMKN - RUAL
GMKN - SMLT
GMKN - SVCB
GMKN - VSEH
HEAD - RTKMP
HEAD - SBER
HEAD - SBERP
HEAD - TATNP
HEAD - TRNFP
HEAD - YDEX
HNFG - LEAS
HNFG - MBNK
HNFG - MOEX
HNFG - RNFT
HNFG - RUAL
HNFG - SVAV
HNFG - TATNP
HNFG - VSEH
HYDR - LENT
HYDR - MAGN
HYDR - MTLR
HYDR - MTLRP
HYDR - PLZL
HYDR - RAGR
HYDR - RTKMP
HYDR - SMLT
HYDR - VSEH
IRAO - MTLRP
IRAO - NLMK
IRAO - PHOR
IRAO - PIKK
IRAO - RASP
IRAO - ROSN
IRAO - RUAL
IRAO - SMLT
IRAO - SNGS
IRAO - SPBE
IRAO - T
IRAO - TRNFP
IRAO - UPRO
IRAO - VTBR
KMAZ - MAGN
KMAZ - PIKK
KMAZ - TRMK
KMAZ - VKCO
LEAS - MBNK
LEAS - MSNG
LEAS - MTLR
LEAS - MTLRP
LEAS - MVID
LEAS - SGZH
LEAS - SNGS
LEAS - TRMK
LEAS - VSEH
LENT - MVID
LENT - PHOR
LENT - SPBE
LENT - T
LENT - VKCO
LENT - VTBR
LKOH - LSRG
LKOH - MAGN
LKOH - NVTK
LKOH - PHOR
LKOH - PLZL
LKOH - RENI
LKOH - RNFT
LKOH - ROSN
LKOH - TATNP
LSRG - MBNK
LSRG - PHOR
LSRG - RAGR
LSRG - ROSN
LSRG - RUAL
LSRG - SPBE
LSRG - TATN
LSRG - TATNP
LSRG - VSEH
MAGN - MBNK
MAGN - MSNG
MAGN - MTLR
MAGN - MTLRP
MAGN - NLMK
MAGN - NVTK
MAGN - PIKK
MAGN - PLZL
MAGN - RASP
MAGN - ROSN
MAGN - RTKM
MAGN - RTKMP
MAGN - RUAL
MAGN - SBER
MAGN - SBERP
MAGN - SELG
MAGN - SNGS
MAGN - SNGSP
MAGN - SVAV
MAGN - TATN
MAGN - TATNP
MAGN - TRMK
MAGN - VKCO
MAGN - VSEH
MAGN - VSMO
MBNK - MOEX
MBNK - MSNG
MBNK - MVID
MBNK - NLMK
MBNK - PHOR
MBNK - RNFT
MBNK - ROSN
MBNK - RTKM
MBNK - SELG
MBNK - SGZH
MBNK - SVAV
MBNK - TATN
MBNK - TATNP
MBNK - VKCO
MBNK - VSEH
MBNK - YDEX
MOEX - PHOR
MOEX - RUAL
MOEX - SPBE
MOEX - VKCO
MOEX - VSEH
MSNG - PHOR
MSNG - RAGR
MSNG - RNFT
MSNG - RTKMP
MSNG - VSEH
MTLR - MTLRP
MTLR - PHOR
MTLR - PIKK
MTLR - PLZL
MTLR - RTKMP
MTLR - SNGS
MTLR - VKCO
MTLR - VSEH
MTLR - YDEX
MTLRP - MTSS
MTLRP - NLMK
MTLRP - NVTK
MTLRP - PIKK
MTLRP - ROSN
MTLRP - RTKM
MTLRP - SNGS
MTLRP - T
MTLRP - UPRO
MTLRP - VKCO
MTLRP - VSEH
MTSS - MVID
MTSS - PHOR
MTSS - PIKK
MTSS - PRMD
MTSS - RASP
MTSS - RTKMP
MTSS - RUAL
MTSS - SMLT
MTSS - SNGS
MTSS - SPBE
MTSS - T
MTSS - TRNFP
MTSS - VKCO
MTSS - VSEH
MTSS - VTBR
MTSS - X5
MVID - PHOR
MVID - RUAL
MVID - SMLT
MVID - SNGS
MVID - VKCO
MVID - VSEH
MVID - YDEX
NLMK - RASP
NLMK - ROSN
NLMK - SNGS
NLMK - VKCO
NLMK - VSEH
NVTK - OZPH
NVTK - PHOR
NVTK - PLZL
NVTK - PRMD
NVTK - RASP
NVTK - ROSN
NVTK - RTKM
NVTK - RUAL
NVTK - SMLT
NVTK - SVCB
NVTK - T
NVTK - YDEX
OZPH - PHOR
OZPH - PRMD
OZPH - RENI
OZPH - SBER
OZPH - SBERP
OZPH - SELG
OZPH - SMLT
OZPH - SPBE
OZPH - T
OZPH - TATN
OZPH - YDEX
PHOR - PIKK
PHOR - PRMD
PHOR - RENI
PHOR - RNFT
PHOR - ROSN
PHOR - RTKM
PHOR - RTKMP
PHOR - RUAL
PHOR - SBER
PHOR - SBERP
PHOR - SELG
PHOR - SNGS
PHOR - SPBE
PHOR - SVAV
PHOR - T
PHOR - TATN
PHOR - TATNP
PHOR - TRMK
PHOR - TRNFP
PHOR - UPRO
PHOR - VKCO
PHOR - VSEH
PHOR - VSMO
PHOR - VTBR
PHOR - WUSH
PHOR - X5
PIKK - PLZL
PIKK - RASP
PIKK - ROSN
PIKK - RUAL
PIKK - SELG
PIKK - SMLT
PIKK - SNGS
PIKK - SPBE
PIKK - VKCO
PIKK - VSMO
PIKK - VTBR
PLZL - ROSN
PLZL - RTKM
PLZL - RTKMP
PLZL - SBER
PLZL - SBERP
PLZL - SELG
PLZL - SNGS
PLZL - SNGSP
PLZL - VKCO
PLZL - VSMO
PRMD - RAGR
PRMD - ROSN
PRMD - SBER
PRMD - SBERP
PRMD - SGZH
PRMD - SMLT
PRMD - SVCB
PRMD - TATN
PRMD - TATNP
PRMD - TRMK
PRMD - VSMO
PRMD - YDEX
RAGR - RNFT
RAGR - ROSN
RAGR - RUAL
RAGR - SELG
RAGR - SNGS
RAGR - TATN
RAGR - TATNP
RAGR - TRMK
RAGR - TRNFP
RAGR - UPRO
RAGR - VSMO
RASP - RNFT
RASP - ROSN
RASP - SMLT
RASP - T
RASP - UPRO
RASP - VKCO
RASP - VTBR
RENI - RUAL
RENI - SBER
RENI - SPBE
RENI - SVAV
RENI - T
RENI - VTBR
RENI - YDEX
RNFT - ROSN
RNFT - RTKM
RNFT - RUAL
RNFT - TRMK
RNFT - TRNFP
RNFT - VKCO
RNFT - WUSH
ROSN - RUAL
ROSN - SBER
ROSN - SBERP
ROSN - SPBE
ROSN - TRNFP
ROSN - VKCO
ROSN - VSEH
ROSN - YDEX
RTKM - RTKMP
RTKM - RUAL
RTKM - SNGS
RTKM - SPBE
RTKM - T
RTKM - TATN
RTKM - TATNP
RTKM - VSEH
RTKMP - RUAL
RTKMP - SMLT
RTKMP - SNGS
RTKMP - SPBE
RTKMP - T
RTKMP - TATN
RTKMP - TATNP
RUAL - SBER
RUAL - SBERP
RUAL - SNGS
RUAL - SPBE
RUAL - SVCB
RUAL - T
RUAL - UPRO
RUAL - VKCO
RUAL - YDEX
SBER - SBERP
SBER - SPBE
SBER - VSEH
SBERP - SPBE
SBERP - VSEH
SBERP - WUSH
SELG - SNGS
SELG - VKCO
SGZH - VSEH
SGZH - YDEX
SMLT - SNGS
SMLT - SVCB
SMLT - T
SMLT - UPRO
SMLT - VKCO
SMLT - VTBR
SMLT - X5
SMLT - YDEX
SNGS - SPBE
SNGS - T
SNGS - TATN
SNGS - TATNP
SNGS - UPRO
SNGS - VKCO
SNGS - VSEH
SNGS - VSMO
SNGS - VTBR
SPBE - T
SPBE - TATNP
SPBE - UPRO
SPBE - VKCO
SPBE - YDEX
SVCB - TATN
SVCB - TATNP
SVCB - VSEH
T - UPRO
T - VKCO
T - VSEH
T - VSMO
T - VTBR
TATN - TATNP
TATN - VSEH
TATN - YDEX
TATNP - VSEH
TATNP - YDEX
TRMK - VKCO
TRMK - VSEH
TRMK - YDEX
UPRO - VSMO
VKCO - VTBR
VSEH - YDEX
VSMO - YDEX
565

In [11]:
# Проверка коинтеграции
coint_results = check_cointegration(merged_data)

In [58]:
# Вывод результатов
c = 0
for pair, result in coint_results.items():
    if result['p-value'] < 0.05:
        c += 1
        print(f"{pair[0]} vs {pair[1]}: p-value = {result['p-value']:.4f}, coint_t = {result['coint_t']:.4f}")
print(c)

AFKS vs CNRU: p-value = 0.0104, coint_t = -3.8838
AFKS vs DATA: p-value = 0.0479, coint_t = -3.3526
AFKS vs DIAS: p-value = 0.0311, coint_t = -3.5152
AFKS vs HEAD: p-value = 0.0030, coint_t = -4.2548
AFKS vs LENT: p-value = 0.0083, coint_t = -3.9542
AFKS vs OZPH: p-value = 0.0380, coint_t = -3.4406
AFKS vs PHOR: p-value = 0.0124, coint_t = -3.8298
AFKS vs PLZL: p-value = 0.0042, coint_t = -4.1568
AFKS vs PRMD: p-value = 0.0023, coint_t = -4.3304
AFKS vs RENI: p-value = 0.0293, coint_t = -3.5359
AFKS vs RTKM: p-value = 0.0049, coint_t = -4.1163
AFKS vs RTKMP: p-value = 0.0257, coint_t = -3.5837
AFKS vs SNGSP: p-value = 0.0023, coint_t = -4.3325
AFKS vs T: p-value = 0.0179, coint_t = -3.7087
AFKS vs VKCO: p-value = 0.0122, coint_t = -3.8334
AFKS vs VTBR: p-value = 0.0439, coint_t = -3.3861
AFKS vs WUSH: p-value = 0.0106, coint_t = -3.8776
AFKS vs X5: p-value = 0.0076, coint_t = -3.9823
AFKS vs YDEX: p-value = 0.0078, coint_t = -3.9753
AFLT vs HNFG: p-value = 0.0132, coint_t = -3.8087
AFLT vs KMAZ: p-value = 0.0418, coint_t = -3.4048
AKRN vs ALRS: p-value = 0.0241, coint_t = -3.6052
AKRN vs BELU: p-value = 0.0076, coint_t = -3.9813
AKRN vs GAZP: p-value = 0.0420, coint_t = -3.4036
AKRN vs MTLR: p-value = 0.0466, coint_t = -3.3630
AKRN vs MVID: p-value = 0.0297, coint_t = -3.5312
AKRN vs NLMK: p-value = 0.0103, coint_t = -3.8886
AKRN vs RAGR: p-value = 0.0168, coint_t = -3.7284
AKRN vs RUAL: p-value = 0.0292, coint_t = -3.5381
AKRN vs SNGS: p-value = 0.0442, coint_t = -3.3841
AKRN vs TRNFP: p-value = 0.0192, coint_t = -3.6845
AKRN vs UPRO: p-value = 0.0463, coint_t = -3.3654
AKRN vs VSEH: p-value = 0.0385, coint_t = -3.4359
AKRN vs VSMO: p-value = 0.0456, coint_t = -3.3717
ALRS vs AQUA: p-value = 0.0016, coint_t = -4.4251
ALRS vs BELU: p-value = 0.0059, coint_t = -4.0615
ALRS vs GAZP: p-value = 0.0180, coint_t = -3.7051
ALRS vs HNFG: p-value = 0.0226, coint_t = -3.6283
ALRS vs LSRG: p-value = 0.0407, coint_t = -3.4156
ALRS vs MTLRP: p-value = 0.0390, coint_t = -3.4316
ALRS vs MVID: p-value = 0.0073, coint_t = -3.9938
ALRS vs NLMK: p-value = 0.0002, coint_t = -4.9854
ALRS vs OZPH: p-value = 0.0239, coint_t = -3.6092
ALRS vs PIKK: p-value = 0.0453, coint_t = -3.3743
ALRS vs RAGR: p-value = 0.0144, coint_t = -3.7807
ALRS vs SNGS: p-value = 0.0061, coint_t = -4.0512
ALRS vs TATN: p-value = 0.0061, coint_t = -4.0472
ALRS vs TATNP: p-value = 0.0064, coint_t = -4.0345
ALRS vs TRNFP: p-value = 0.0282, coint_t = -3.5501
ALRS vs UPRO: p-value = 0.0104, coint_t = -3.8862
ALRS vs VSEH: p-value = 0.0111, coint_t = -3.8631
AQUA vs BELU: p-value = 0.0283, coint_t = -3.5484
AQUA vs MTLR: p-value = 0.0227, coint_t = -3.6262
AQUA vs MVID: p-value = 0.0170, coint_t = -3.7252
AQUA vs NLMK: p-value = 0.0051, coint_t = -4.1024
BELU vs GAZP: p-value = 0.0239, coint_t = -3.6085
BELU vs KMAZ: p-value = 0.0491, coint_t = -3.3432
BELU vs LKOH: p-value = 0.0202, coint_t = -3.6674
BELU vs MSNG: p-value = 0.0284, coint_t = -3.5482
BELU vs MVID: p-value = 0.0011, coint_t = -4.5233
BELU vs NLMK: p-value = 0.0215, coint_t = -3.6455
BELU vs PIKK: p-value = 0.0246, coint_t = -3.5986
BELU vs TATN: p-value = 0.0086, coint_t = -3.9454
BELU vs TATNP: p-value = 0.0007, coint_t = -4.6408
BELU vs TRNFP: p-value = 0.0010, coint_t = -4.5511
BELU vs VSEH: p-value = 0.0093, coint_t = -3.9196
CBOM vs FLOT: p-value = 0.0003, coint_t = -4.8630
CHMF vs ENPG: p-value = 0.0122, coint_t = -3.8341
CHMF vs LENT: p-value = 0.0408, coint_t = -3.4138
CHMF vs LSRG: p-value = 0.0372, coint_t = -3.4490
CHMF vs MBNK: p-value = 0.0041, coint_t = -4.1684
CHMF vs OZPH: p-value = 0.0177, coint_t = -3.7123
CHMF vs PLZL: p-value = 0.0425, coint_t = -3.3991
CHMF vs T: p-value = 0.0156, coint_t = -3.7535
CHMF vs YDEX: p-value = 0.0079, coint_t = -3.9723
CNRU vs DATA: p-value = 0.0193, coint_t = -3.6820
CNRU vs DIAS: p-value = 0.0399, coint_t = -3.4226
CNRU vs LENT: p-value = 0.0237, coint_t = -3.6119
CNRU vs PLZL: p-value = 0.0019, coint_t = -4.3793
CNRU vs RENI: p-value = 0.0081, coint_t = -3.9650
CNRU vs RTKM: p-value = 0.0163, coint_t = -3.7386
CNRU vs SNGSP: p-value = 0.0112, coint_t = -3.8624
CNRU vs T: p-value = 0.0130, coint_t = -3.8148
CNRU vs VKCO: p-value = 0.0148, coint_t = -3.7723
CNRU vs WUSH: p-value = 0.0027, coint_t = -4.2829
CNRU vs X5: p-value = 0.0472, coint_t = -3.3582
DIAS vs KMAZ: p-value = 0.0034, coint_t = -4.2189
DIAS vs PIKK: p-value = 0.0147, coint_t = -3.7737
DIAS vs VKCO: p-value = 0.0327, coint_t = -3.4962
ENPG vs GMKN: p-value = 0.0000, coint_t = -5.4609
ENPG vs HEAD: p-value = 0.0218, coint_t = -3.6406
ENPG vs IVAT: p-value = 0.0221, coint_t = -3.6361
ENPG vs LENT: p-value = 0.0055, coint_t = -4.0827
ENPG vs OZPH: p-value = 0.0225, coint_t = -3.6300
ENPG vs PHOR: p-value = 0.0045, coint_t = -4.1417
ENPG vs PLZL: p-value = 0.0000, coint_t = -5.4792
ENPG vs PRMD: p-value = 0.0493, coint_t = -3.3413
ENPG vs RENI: p-value = 0.0193, coint_t = -3.6832
ENPG vs RTKMP: p-value = 0.0092, coint_t = -3.9222
ENPG vs SNGSP: p-value = 0.0180, coint_t = -3.7064
ENPG vs VKCO: p-value = 0.0433, coint_t = -3.3912
EUTR vs HEAD: p-value = 0.0312, coint_t = -3.5139
EUTR vs HNFG: p-value = 0.0472, coint_t = -3.3585
EUTR vs IRAO: p-value = 0.0290, coint_t = -3.5402
EUTR vs KMAZ: p-value = 0.0472, coint_t = -3.3586
EUTR vs LENT: p-value = 0.0064, coint_t = -4.0337
EUTR vs MBNK: p-value = 0.0295, coint_t = -3.5338
EUTR vs MTLR: p-value = 0.0350, coint_t = -3.4718
EUTR vs MTLRP: p-value = 0.0450, coint_t = -3.3764
EUTR vs OZPH: p-value = 0.0368, coint_t = -3.4526
EUTR vs PHOR: p-value = 0.0095, coint_t = -3.9149
EUTR vs PIKK: p-value = 0.0300, coint_t = -3.5280
EUTR vs PLZL: p-value = 0.0075, coint_t = -3.9865
EUTR vs RAGR: p-value = 0.0456, coint_t = -3.3714
EUTR vs RTKM: p-value = 0.0480, coint_t = -3.3519
EUTR vs RTKMP: p-value = 0.0406, coint_t = -3.4159
EUTR vs SBER: p-value = 0.0328, coint_t = -3.4950
EUTR vs SBERP: p-value = 0.0298, coint_t = -3.5307
EUTR vs SNGSP: p-value = 0.0411, coint_t = -3.4112
EUTR vs SVAV: p-value = 0.0291, coint_t = -3.5394
EUTR vs VKCO: p-value = 0.0339, coint_t = -3.4831
EUTR vs VSEH: p-value = 0.0416, coint_t = -3.4069
EUTR vs WUSH: p-value = 0.0183, coint_t = -3.7002
FLOT vs GMKN: p-value = 0.0446, coint_t = -3.3801
FLOT vs LENT: p-value = 0.0321, coint_t = -3.5031
FLOT vs OZPH: p-value = 0.0001, coint_t = -5.0684
FLOT vs PHOR: p-value = 0.0432, coint_t = -3.3924
FLOT vs PLZL: p-value = 0.0094, coint_t = -3.9162
GAZP vs RAGR: p-value = 0.0053, coint_t = -4.0934
GAZP vs SNGS: p-value = 0.0263, coint_t = -3.5743
GMKN vs IVAT: p-value = 0.0294, coint_t = -3.5354
GMKN vs LENT: p-value = 0.0174, coint_t = -3.7172
GMKN vs PLZL: p-value = 0.0044, coint_t = -4.1441
GMKN vs SNGSP: p-value = 0.0346, coint_t = -3.4754
HEAD vs RENI: p-value = 0.0301, coint_t = -3.5265
HEAD vs SNGSP: p-value = 0.0150, coint_t = -3.7659
HEAD vs VKCO: p-value = 0.0006, coint_t = -4.6925
HNFG vs IRAO: p-value = 0.0225, coint_t = -3.6302
HNFG vs KMAZ: p-value = 0.0101, coint_t = -3.8928
HNFG vs MTLRP: p-value = 0.0037, coint_t = -4.1941
HNFG vs PIKK: p-value = 0.0239, coint_t = -3.6085
HNFG vs RASP: p-value = 0.0007, coint_t = -4.6283
HYDR vs IRAO: p-value = 0.0113, coint_t = -3.8584
HYDR vs IVAT: p-value = 0.0088, coint_t = -3.9372
HYDR vs KMAZ: p-value = 0.0081, coint_t = -3.9636
HYDR vs LEAS: p-value = 0.0075, coint_t = -3.9850
HYDR vs LENT: p-value = 0.0114, coint_t = -3.8552
HYDR vs LKOH: p-value = 0.0314, coint_t = -3.5111
HYDR vs LSRG: p-value = 0.0238, coint_t = -3.6106
HYDR vs MAGN: p-value = 0.0210, coint_t = -3.6539
HYDR vs MBNK: p-value = 0.0121, coint_t = -3.8376
HYDR vs MOEX: p-value = 0.0041, coint_t = -4.1676
HYDR vs MSNG: p-value = 0.0043, coint_t = -4.1549
HYDR vs MTSS: p-value = 0.0025, coint_t = -4.3061
HYDR vs MVID: p-value = 0.0208, coint_t = -3.6574
HYDR vs NLMK: p-value = 0.0281, coint_t = -3.5517
HYDR vs OZPH: p-value = 0.0087, coint_t = -3.9426
HYDR vs PHOR: p-value = 0.0105, coint_t = -3.8833
HYDR vs PIKK: p-value = 0.0035, coint_t = -4.2091
HYDR vs PLZL: p-value = 0.0105, coint_t = -3.8808
HYDR vs PRMD: p-value = 0.0112, coint_t = -3.8620
HYDR vs RAGR: p-value = 0.0034, coint_t = -4.2167
HYDR vs RASP: p-value = 0.0266, coint_t = -3.5712
HYDR vs RENI: p-value = 0.0037, coint_t = -4.1977
HYDR vs RNFT: p-value = 0.0172, coint_t = -3.7205
HYDR vs RTKM: p-value = 0.0094, coint_t = -3.9160
HYDR vs RTKMP: p-value = 0.0026, coint_t = -4.2929
HYDR vs RUAL: p-value = 0.0255, coint_t = -3.5864
HYDR vs SBER: p-value = 0.0179, coint_t = -3.7080
HYDR vs SBERP: p-value = 0.0187, coint_t = -3.6925
HYDR vs SELG: p-value = 0.0200, coint_t = -3.6696
HYDR vs SGZH: p-value = 0.0193, coint_t = -3.6826
HYDR vs SMLT: p-value = 0.0064, coint_t = -4.0369
HYDR vs SNGSP: p-value = 0.0129, coint_t = -3.8165
HYDR vs SPBE: p-value = 0.0043, coint_t = -4.1554
HYDR vs SVAV: p-value = 0.0030, coint_t = -4.2525
HYDR vs SVCB: p-value = 0.0015, coint_t = -4.4491
HYDR vs T: p-value = 0.0154, coint_t = -3.7581
HYDR vs TATN: p-value = 0.0093, coint_t = -3.9212
HYDR vs TATNP: p-value = 0.0075, coint_t = -3.9863
HYDR vs TRNFP: p-value = 0.0048, coint_t = -4.1205
HYDR vs UPRO: p-value = 0.0128, coint_t = -3.8174
HYDR vs VKCO: p-value = 0.0032, coint_t = -4.2379
HYDR vs VSEH: p-value = 0.0077, coint_t = -3.9802
HYDR vs VTBR: p-value = 0.0051, coint_t = -4.1050
HYDR vs WUSH: p-value = 0.0414, coint_t = -3.4089
HYDR vs X5: p-value = 0.0051, coint_t = -4.1019
HYDR vs YDEX: p-value = 0.0115, coint_t = -3.8544
IRAO vs KMAZ: p-value = 0.0260, coint_t = -3.5791
IRAO vs PIKK: p-value = 0.0198, coint_t = -3.6736
KMAZ vs MOEX: p-value = 0.0368, coint_t = -3.4532
KMAZ vs PIKK: p-value = 0.0002, coint_t = -4.9825
KMAZ vs RASP: p-value = 0.0140, coint_t = -3.7903
KMAZ vs RENI: p-value = 0.0245, coint_t = -3.6001
KMAZ vs T: p-value = 0.0263, coint_t = -3.5748
KMAZ vs VKCO: p-value = 0.0051, coint_t = -4.1052
KMAZ vs VSEH: p-value = 0.0307, coint_t = -3.5196
LEAS vs LSRG: p-value = 0.0167, coint_t = -3.7322
LEAS vs MAGN: p-value = 0.0167, coint_t = -3.7314
LEAS vs PLZL: p-value = 0.0303, coint_t = -3.5239
LEAS vs RENI: p-value = 0.0283, coint_t = -3.5495
LEAS vs RTKMP: p-value = 0.0200, coint_t = -3.6703
LEAS vs SELG: p-value = 0.0297, coint_t = -3.5313
LEAS vs SNGSP: p-value = 0.0354, coint_t = -3.4674
LEAS vs SVCB: p-value = 0.0105, coint_t = -3.8813
LEAS vs T: p-value = 0.0341, coint_t = -3.4811
LEAS vs VTBR: p-value = 0.0098, coint_t = -3.9040
LEAS vs YDEX: p-value = 0.0055, coint_t = -4.0813
LKOH vs MSNG: p-value = 0.0400, coint_t = -3.4213
LKOH vs PIKK: p-value = 0.0477, coint_t = -3.3543
LKOH vs SVAV: p-value = 0.0238, coint_t = -3.6096
LKOH vs TRNFP: p-value = 0.0127, coint_t = -3.8211
LSRG vs MBNK: p-value = 0.0015, coint_t = -4.4396
LSRG vs MOEX: p-value = 0.0315, coint_t = -3.5105
LSRG vs MSNG: p-value = 0.0136, coint_t = -3.7984
LSRG vs MTSS: p-value = 0.0235, coint_t = -3.6144
LSRG vs MVID: p-value = 0.0336, coint_t = -3.4869
LSRG vs NLMK: p-value = 0.0128, coint_t = -3.8193
LSRG vs NVTK: p-value = 0.0009, coint_t = -4.5750
LSRG vs OZPH: p-value = 0.0003, coint_t = -4.8525
LSRG vs PHOR: p-value = 0.0022, coint_t = -4.3444
LSRG vs PIKK: p-value = 0.0214, coint_t = -3.6470
LSRG vs PLZL: p-value = 0.0008, coint_t = -4.5990
LSRG vs PRMD: p-value = 0.0156, coint_t = -3.7532
LSRG vs RAGR: p-value = 0.0162, coint_t = -3.7406
LSRG vs RENI: p-value = 0.0089, coint_t = -3.9332
LSRG vs ROSN: p-value = 0.0010, coint_t = -4.5607
LSRG vs RTKM: p-value = 0.0034, coint_t = -4.2175
LSRG vs RTKMP: p-value = 0.0112, coint_t = -3.8621
LSRG vs RUAL: p-value = 0.0022, coint_t = -4.3359
LSRG vs SBER: p-value = 0.0211, coint_t = -3.6524
LSRG vs SBERP: p-value = 0.0212, coint_t = -3.6511
LSRG vs SELG: p-value = 0.0118, coint_t = -3.8454
LSRG vs SGZH: p-value = 0.0066, coint_t = -4.0257
LSRG vs SMLT: p-value = 0.0327, coint_t = -3.4961
LSRG vs SNGS: p-value = 0.0017, coint_t = -4.4166
LSRG vs SNGSP: p-value = 0.0076, coint_t = -3.9833
LSRG vs SPBE: p-value = 0.0078, coint_t = -3.9763
LSRG vs SVAV: p-value = 0.0268, coint_t = -3.5684
LSRG vs SVCB: p-value = 0.0418, coint_t = -3.4053
LSRG vs T: p-value = 0.0077, coint_t = -3.9798
LSRG vs TATN: p-value = 0.0057, coint_t = -4.0694
LSRG vs TATNP: p-value = 0.0061, coint_t = -4.0475
LSRG vs TRMK: p-value = 0.0363, coint_t = -3.4577
LSRG vs TRNFP: p-value = 0.0180, coint_t = -3.7060
LSRG vs UPRO: p-value = 0.0043, coint_t = -4.1518
LSRG vs VKCO: p-value = 0.0139, coint_t = -3.7919
LSRG vs VSEH: p-value = 0.0392, coint_t = -3.4291
LSRG vs VSMO: p-value = 0.0083, coint_t = -3.9545
LSRG vs VTBR: p-value = 0.0028, coint_t = -4.2759
LSRG vs WUSH: p-value = 0.0387, coint_t = -3.4338
LSRG vs X5: p-value = 0.0208, coint_t = -3.6576
LSRG vs YDEX: p-value = 0.0021, coint_t = -4.3579
MAGN vs PLZL: p-value = 0.0246, coint_t = -3.5984
MAGN vs RENI: p-value = 0.0145, coint_t = -3.7780
MAGN vs RTKMP: p-value = 0.0267, coint_t = -3.5696
MAGN vs SNGSP: p-value = 0.0479, coint_t = -3.3529
MAGN vs VTBR: p-value = 0.0092, coint_t = -3.9242
MAGN vs YDEX: p-value = 0.0134, coint_t = -3.8037
MBNK vs OZPH: p-value = 0.0270, coint_t = -3.5651
MBNK vs PLZL: p-value = 0.0477, coint_t = -3.3541
MOEX vs PIKK: p-value = 0.0109, coint_t = -3.8705
MOEX vs RASP: p-value = 0.0389, coint_t = -3.4322
MOEX vs RTKMP: p-value = 0.0248, coint_t = -3.5954
MOEX vs VKCO: p-value = 0.0218, coint_t = -3.6408
MSNG vs MTSS: p-value = 0.0386, coint_t = -3.4351
MSNG vs RAGR: p-value = 0.0368, coint_t = -3.4525
MSNG vs SPBE: p-value = 0.0471, coint_t = -3.3592
MTLR vs MTSS: p-value = 0.0022, coint_t = -4.3468
MTLR vs MVID: p-value = 0.0004, coint_t = -4.8184
MTLR vs NLMK: p-value = 0.0097, coint_t = -3.9065
MTLR vs NVTK: p-value = 0.0252, coint_t = -3.5906
MTLR vs OZPH: p-value = 0.0011, coint_t = -4.5205
MTLR vs PHOR: p-value = 0.0019, coint_t = -4.3830
MTLR vs PIKK: p-value = 0.0004, coint_t = -4.8133
MTLR vs PLZL: p-value = 0.0021, coint_t = -4.3602
MTLR vs PRMD: p-value = 0.0013, coint_t = -4.4892
MTLR vs RAGR: p-value = 0.0304, coint_t = -3.5235
MTLR vs RASP: p-value = 0.0143, coint_t = -3.7819
MTLR vs RENI: p-value = 0.0024, coint_t = -4.3148
MTLR vs ROSN: p-value = 0.0094, coint_t = -3.9185
MTLR vs RTKM: p-value = 0.0029, coint_t = -4.2611
MTLR vs RTKMP: p-value = 0.0022, coint_t = -4.3437
MTLR vs SBER: p-value = 0.0009, coint_t = -4.5675
MTLR vs SBERP: p-value = 0.0010, coint_t = -4.5544
MTLR vs SELG: p-value = 0.0048, coint_t = -4.1219
MTLR vs SGZH: p-value = 0.0044, coint_t = -4.1490
MTLR vs SMLT: p-value = 0.0046, coint_t = -4.1348
MTLR vs SNGSP: p-value = 0.0018, coint_t = -4.3986
MTLR vs SPBE: p-value = 0.0064, coint_t = -4.0329
MTLR vs SVAV: p-value = 0.0044, coint_t = -4.1456
MTLR vs SVCB: p-value = 0.0025, coint_t = -4.3086
MTLR vs T: p-value = 0.0036, coint_t = -4.2039
MTLR vs TATN: p-value = 0.0001, coint_t = -5.0246
MTLR vs TATNP: p-value = 0.0001, coint_t = -5.1399
MTLR vs TRNFP: p-value = 0.0009, coint_t = -4.5841
MTLR vs UPRO: p-value = 0.0193, coint_t = -3.6828
MTLR vs VKCO: p-value = 0.0015, coint_t = -4.4534
MTLR vs VSEH: p-value = 0.0011, coint_t = -4.5341
MTLR vs VSMO: p-value = 0.0120, coint_t = -3.8384
MTLR vs VTBR: p-value = 0.0024, coint_t = -4.3166
MTLR vs WUSH: p-value = 0.0114, coint_t = -3.8551
MTLR vs X5: p-value = 0.0023, coint_t = -4.3324
MTLR vs YDEX: p-value = 0.0078, coint_t = -3.9728
MTLRP vs MTSS: p-value = 0.0099, coint_t = -3.9012
MTLRP vs MVID: p-value = 0.0001, coint_t = -5.2191
MTLRP vs NLMK: p-value = 0.0394, coint_t = -3.4271
MTLRP vs OZPH: p-value = 0.0063, coint_t = -4.0381
MTLRP vs PHOR: p-value = 0.0118, coint_t = -3.8437
MTLRP vs PIKK: p-value = 0.0000, coint_t = -5.6502
MTLRP vs PLZL: p-value = 0.0111, coint_t = -3.8654
MTLRP vs PRMD: p-value = 0.0038, coint_t = -4.1898
MTLRP vs RASP: p-value = 0.0110, coint_t = -3.8681
MTLRP vs RENI: p-value = 0.0037, coint_t = -4.1994
MTLRP vs ROSN: p-value = 0.0277, coint_t = -3.5562
MTLRP vs RTKM: p-value = 0.0039, coint_t = -4.1800
MTLRP vs RTKMP: p-value = 0.0038, coint_t = -4.1857
MTLRP vs SBER: p-value = 0.0015, coint_t = -4.4450
MTLRP vs SBERP: p-value = 0.0018, coint_t = -4.3991
MTLRP vs SELG: p-value = 0.0319, coint_t = -3.5052
MTLRP vs SGZH: p-value = 0.0117, coint_t = -3.8482
MTLRP vs SMLT: p-value = 0.0041, coint_t = -4.1655
MTLRP vs SNGSP: p-value = 0.0030, coint_t = -4.2531
MTLRP vs SVAV: p-value = 0.0100, coint_t = -3.8964
MTLRP vs SVCB: p-value = 0.0106, coint_t = -3.8795
MTLRP vs T: p-value = 0.0023, coint_t = -4.3322
MTLRP vs TRNFP: p-value = 0.0007, coint_t = -4.6392
MTLRP vs VKCO: p-value = 0.0007, coint_t = -4.6596
MTLRP vs VSEH: p-value = 0.0003, coint_t = -4.8626
MTLRP vs VTBR: p-value = 0.0094, coint_t = -3.9165
MTLRP vs WUSH: p-value = 0.0377, coint_t = -3.4440
MTLRP vs X5: p-value = 0.0036, coint_t = -4.2075
MTLRP vs YDEX: p-value = 0.0099, coint_t = -3.9018
MVID vs VSEH: p-value = 0.0009, coint_t = -4.5859
NLMK vs TATN: p-value = 0.0063, coint_t = -4.0398
NLMK vs TATNP: p-value = 0.0041, coint_t = -4.1670
NVTK vs OZPH: p-value = 0.0163, coint_t = -3.7383
NVTK vs RAGR: p-value = 0.0304, coint_t = -3.5233
NVTK vs RUAL: p-value = 0.0152, coint_t = -3.7631
NVTK vs SNGS: p-value = 0.0235, coint_t = -3.6141
NVTK vs VSMO: p-value = 0.0168, coint_t = -3.7302
PHOR vs SGZH: p-value = 0.0282, coint_t = -3.5499
PIKK vs RASP: p-value = 0.0133, coint_t = -3.8055
PIKK vs WUSH: p-value = 0.0031, coint_t = -4.2462
PLZL vs RTKM: p-value = 0.0034, coint_t = -4.2205
PLZL vs YDEX: p-value = 0.0486, coint_t = -3.3472
PRMD vs RASP: p-value = 0.0466, coint_t = -3.3630
PRMD vs RENI: p-value = 0.0453, coint_t = -3.3738
PRMD vs SBER: p-value = 0.0208, coint_t = -3.6573
PRMD vs SBERP: p-value = 0.0187, coint_t = -3.6929
PRMD vs SNGSP: p-value = 0.0169, coint_t = -3.7277
PRMD vs T: p-value = 0.0255, coint_t = -3.5856
PRMD vs WUSH: p-value = 0.0263, coint_t = -3.5748
RAGR vs ROSN: p-value = 0.0450, coint_t = -3.3767
RAGR vs UPRO: p-value = 0.0341, coint_t = -3.4810
RAGR vs VSMO: p-value = 0.0243, coint_t = -3.6032
RASP vs RTKM: p-value = 0.0350, coint_t = -3.4714
RASP vs RTKMP: p-value = 0.0296, coint_t = -3.5332
RASP vs TATN: p-value = 0.0462, coint_t = -3.3662
RASP vs TATNP: p-value = 0.0315, coint_t = -3.5103
RASP vs TRNFP: p-value = 0.0323, coint_t = -3.5016
RASP vs VKCO: p-value = 0.0059, coint_t = -4.0590
RASP vs VSEH: p-value = 0.0048, coint_t = -4.1223
RASP vs WUSH: p-value = 0.0378, coint_t = -3.4432
RASP vs X5: p-value = 0.0214, coint_t = -3.6473
RENI vs VKCO: p-value = 0.0252, coint_t = -3.5905
RENI vs YDEX: p-value = 0.0425, coint_t = -3.3984
RNFT vs ROSN: p-value = 0.0001, coint_t = -5.2096
RNFT vs RTKM: p-value = 0.0007, coint_t = -4.6474
RNFT vs RTKMP: p-value = 0.0006, coint_t = -4.7001
RNFT vs SBER: p-value = 0.0003, coint_t = -4.8641
RNFT vs SBERP: p-value = 0.0003, coint_t = -4.8576
RNFT vs SELG: p-value = 0.0017, coint_t = -4.4059
RNFT vs SGZH: p-value = 0.0005, coint_t = -4.7517
RNFT vs SMLT: p-value = 0.0014, coint_t = -4.4564
RNFT vs SNGS: p-value = 0.0023, coint_t = -4.3349
RNFT vs SNGSP: p-value = 0.0007, coint_t = -4.6423
RNFT vs SPBE: p-value = 0.0026, coint_t = -4.2912
RNFT vs SVAV: p-value = 0.0039, coint_t = -4.1778
RNFT vs SVCB: p-value = 0.0012, coint_t = -4.5031
RNFT vs T: p-value = 0.0013, coint_t = -4.4761
RNFT vs TATN: p-value = 0.0001, coint_t = -5.1476
RNFT vs TATNP: p-value = 0.0001, coint_t = -5.0851
RNFT vs TRMK: p-value = 0.0025, coint_t = -4.3121
RNFT vs TRNFP: p-value = 0.0006, coint_t = -4.7027
RNFT vs UPRO: p-value = 0.0011, coint_t = -4.5384
RNFT vs VKCO: p-value = 0.0005, coint_t = -4.7206
RNFT vs VSEH: p-value = 0.0019, coint_t = -4.3829
RNFT vs VSMO: p-value = 0.0067, coint_t = -4.0208
RNFT vs VTBR: p-value = 0.0039, coint_t = -4.1828
RNFT vs WUSH: p-value = 0.0490, coint_t = -3.3433
RNFT vs X5: p-value = 0.0003, coint_t = -4.8200
RNFT vs YDEX: p-value = 0.0018, coint_t = -4.4033
ROSN vs RUAL: p-value = 0.0342, coint_t = -3.4805
ROSN vs UPRO: p-value = 0.0190, coint_t = -3.6876
ROSN vs VSMO: p-value = 0.0432, coint_t = -3.3928
RTKMP vs X5: p-value = 0.0285, coint_t = -3.5467
RUAL vs SPBE: p-value = 0.0122, coint_t = -3.8341
RUAL vs TATN: p-value = 0.0101, coint_t = -3.8932